# Generated by Django 2.1.7 on 2019-03-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190321_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='date_joined',
            field=models.DateTimeField(null=True),
        ),
    ]
