# Generated by Django 2.1.7 on 2019-03-21 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_matatu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_type', models.CharField(choices=[('driver', 'Driver'), ('tout', 'Tout')], max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('id_number', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('age', models.IntegerField()),
                ('driver_license_type', models.CharField(choices=[('category_a', 'Category A'), ('category_b', 'Category B'), ('category_c', 'Category C')], max_length=100)),
                ('driver_license_number', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='crew_pics')),
                ('date_added', models.DateTimeField(null=True)),
                ('matatu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Matatu')),
            ],
        ),
    ]
