# Generated by Django 2.1.7 on 2019-03-21 13:41

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_crew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
