# Generated by Django 2.1.7 on 2019-03-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_activity_log_date_and_time_the_activity_took_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_log',
            name='number_of_trips_made_until_now',
        ),
    ]
