# Generated by Django 2.1.7 on 2019-03-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_activity_log_number_of_trips_made_until_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_log',
            name='number_of_trips_made_until_now',
            field=models.IntegerField(null=True),
        ),
    ]
