# Generated by Django 2.1.7 on 2019-03-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_matatu_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='matatu',
            name='number_of_seats',
            field=models.IntegerField(null=True),
        ),
    ]
