# Generated by Django 2.1.7 on 2019-03-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_activity_log_place_the_activity_took_pace'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity_log',
            name='Place_the_Activity_happened',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
