# Generated by Django 2.1.7 on 2019-03-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_activity_log_place_the_activity_happened'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity_log',
            old_name='matatu_id',
            new_name='matatu',
        ),
        migrations.RenameField(
            model_name='crew',
            old_name='matatu_id',
            new_name='matatu',
        ),
        migrations.RenameField(
            model_name='finance',
            old_name='matatu_id',
            new_name='matatu',
        ),
        migrations.RenameField(
            model_name='matatu',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
