# Generated by Django 2.1.7 on 2019-03-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190325_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matatu',
            name='reg_number',
            field=models.CharField(max_length=50),
        ),
    ]
